name: Link Project
on:
  issues:
    types: [opened]
jobs:
  link-project:
    steps:
      - uses: actions/add-to-project@v2.0.0
          with:
            project-url: 'https://github.com/users/Melanthiaceae/projects/1'
            github-token: ${{ secrets.PAT }}
